### ISSUE TITLE
Support cuda

### ISSUE THREAD

**Issue by chengren** [MaartenGr/PolyFuzz#15]
Does the current package support GPU or are there any ways to call cuda?

**Comment by MaartenGr** [comment]
That depends on the underlying model. If you are using Flair, then the model is automatically executed on the GPU if it is available. You can also specify the device as such:

```python
import flair, torch
flair.device = torch.device('cpu') 
```

All other models, such as TF-IDF and Levenshtein do not support GPU-based processing.
