### ISSUE TITLE
Error when using top_n in Embeddings

### ISSUE THREAD

**Issue by stuartong** [MaartenGr/PolyFuzz#18]
Great library really loving it but I am running into the following error - any ideas why?

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-44-798ef3c0b5bc> in <module>
      2 
      3 embeddings = TransformerWordEmbeddings('bert-base-multilingual-cased')
----> 4 bert = Embeddings(embeddings, min_similarity=0,top_n=3 ,model_id="BERT",)
      5 tfidf = TFIDF(min_similarity=0)
      6 edit = EditDistance()

TypeError: __init__() got an unexpected keyword argument 'top_n'
`

**Comment by MaartenGr** [comment]
Which version of PolyFuzz are you using? The `top_n`  feature was implemented in v0.3 and was not available in earlier versions.

**Comment by stuartong** [comment]
Ah yes - it appears I have 0.2.2 installed
