### ISSUE TITLE
Broken first example?

### ISSUE THREAD

**Issue by colasri** [MaartenGr/PolyFuzz#39]
Trying to run the first example of [the tutorial](https://maartengr.github.io/PolyFuzz/tutorial/models/models/#tf-idf):

```python
from polyfuzz.models import TFIDF
from polyfuzz import PolyFuzz

from_list = ["apple", "apples", "appl", "recal", "house", "similarity"]
to_list = ["apple", "apples", "mouse"]

tfidf = TFIDF(n_gram_range=(3, 3), min_similarity=0, matcher_id="TF-IDF")
model = PolyFuzz(tfidf).match(from_list, to_list)
```

I get the following error:

```log
----> 7 tfidf = TFIDF(n_gram_range=(3, 3), min_similarity=0, matcher_id="TF-IDF")

TypeError: TFIDF.__init__() got an unexpected keyword argument 'matcher_id'
```

I see indeed no such argument in [TFIDF.__init__](https://github.com/MaartenGr/PolyFuzz/blob/9d373a8d182481ed02f5c1742b28df076b441364/polyfuzz/models/_tfidf.py#L48).

It's just a typo, `matcher_id` should be `model_id`, or am I missing something?

**Comment by MaartenGr** [comment]
Yes, it is indeed a typo. Thank you for pointing that out. I just updated the documentation and made sure it was fixed!
