### ISSUE TITLE
pip doesn't found packages when using any of the [name] "variants"

### ISSUE THREAD

**Issue by matrs** [MaartenGr/PolyFuzz#46]
Hello,
I've installed PolyFuzz more than once, but I've never been able to install it using any of the `[variant-name]` options:
```sh
$ pip install polyfuzz[fast]                                                                                                ✔  py310  
zsh: no matches found: polyfuzz[fast]
$ pip install polyfuzz[sbert]                                                                                             1 ✘  py310  
zsh: no matches found: polyfuzz[sbert]
```
Maybe I'm misunderstanding something about that option.  
I'm in `linux` with `pip 22.2.2` and `python 3.10`, but a couple a months ago It was the same with `python 3.8` and an older `pip` version.

**Comment by MaartenGr** [comment]
That is because of how `zsh` does pattern matching. You should install it as follows:

```pip install 'polyfuzz[fast]'```

You can find more about that [here](https://stackoverflow.com/a/30539963). Let me know if it works for you!

**Comment by matrs** [comment]
Thank you @MaartenGr , that worked :+1: . I just changed to zsh a few months ago and I use `conda` most of the time, so i think this is my first time using a pip package with `[]`.
