### ISSUE TITLE
Getting argmax of empty sequence

### ISSUE THREAD

**Issue by ashczq** [MaartenGr/PolyFuzz#53]
![image](https://user-images.githubusercontent.com/49942750/204536074-6c2aab82-665e-493b-99e0-aa73c0d90944.png)

I'm currently using the levenshtein distance through Edit Distance and getting this error. Have checked my list values for null values as well as empty strings. The same list values work with fuzz_matcher & TF-IDF. Any idea why this is happening?

**Comment by MaartenGr** [comment]
Apologies for the late response. Could you give me the full code and perhaps a reproducible example? Without it, it is difficult to see what exactly is happening.

**Comment by ashczq** [comment]
```
jellyfish_matcher = EditDistance(scorer=levenshtein_distance)
company_names = ['shift capital',' blackstone real estate private equity','shift capital llc','brokertec','axience']
model = PolyFuzz(jellyfish_matcher)
model.match(company_names)
```
![image](https://user-images.githubusercontent.com/49942750/205867981-e7cf3100-4492-488e-bf83-9a948c3cd535.png)

Sure i've included an example and also a screenshot of the initial error that results in the argmax error.

**Comment by MaartenGr** [comment]
It took a while, my apologies, but it seems that the issue stems from the implementation of the EditDistance in PolyFuzz. I just added a fix to the main branch that you can use. I might release an official quickfix in the coming weeks but that will also depends on whether new features are going to be implemented.
