### ISSUE TITLE
Usage of logging instead of logger

### ISSUE THREAD

**Issue by 6801318d8d** [MaartenGr/PolyFuzz#66]
I don't understand why [here](https://github.com/MaartenGr/PolyFuzz/blob/master/polyfuzz/polyfuzz.py#L144) and [here](https://github.com/MaartenGr/PolyFuzz/blob/master/polyfuzz/polyfuzz.py#L144) we use `logging` instead of `logger`, thus relying on the root logger which I use for my own purposes.

**Comment by MaartenGr** [comment]
Ah, that's most likely a mistake and should indeed be logger. If you want, a PR would be appreciated!
