### ISSUE TITLE
model_id logging

### ISSUE THREAD

**Issue by raffaem** [MaartenGr/PolyFuzz#69]
I keep getting "Ran model with model id = None" logs.

And I don't understand why in the [examples](https://maartengr.github.io/PolyFuzz/api/polyfuzz/#polyfuzz.polyfuzz.PolyFuzz.fit) there is a `model_id` passed to the constructor of `PolyFuzz` while this constructor [do not take this argument](https://maartengr.github.io/PolyFuzz/api/polyfuzz/#polyfuzzpolyfuzzpolyfuzz)

**Comment by MaartenGr** [comment]
It is difficult to say without seeing the code. Having said, the documentation you refer to simply seems to be an artifact of old documentation and indeed should be updated.

**Comment by raffaem** [comment]
The code is this.

It also starts to log from the second call onwards for some reason:

```
➜ python
Python 3.12.0 (main, Nov 10 2023, 22:38:47) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.basicConfig(level=logging.INFO, force=True)
>>> from polyfuzz import PolyFuzz
>>> model = PolyFuzz("EditDistance")
>>> model.match(["hello"], ["hi"])
<polyfuzz.polyfuzz.PolyFuzz object at 0x7f20b4232b10>
>>> model.match(["hello"], ["hi"])
INFO:root:Ran model with model id = None
<polyfuzz.polyfuzz.PolyFuzz object at 0x7f20b4232b10>
>>> model.match(["hello"], ["hi"])
INFO:root:Ran model with model id = None
<polyfuzz.polyfuzz.PolyFuzz object at 0x7f20b4232b10>
```

**Comment by raffaem** [comment]
I think I have installed from pip, which don't have https://github.com/MaartenGr/PolyFuzz/commit/e7540030d6dddc64bdb94c474ed6360dd7a5cdf7

**Comment by MaartenGr** [comment]
Thanks for sharing, I can only reproduce this issue with the following added:

```python
import logging
logging.basicConfig(level=logging.INFO, force=True)
```

Which is not supported behavior for PolyFuzz. To work with the verbosity, use the `verbose` parameter instead.
